### PR TITLE
Fixed broken web URLs

### PR DESCRIPTION
**Pull request by ksanjeet**
This fixes broken web URLs on 11 check files.

### CODE REVIEW

**Review by dottorblaster — APPROVED** [review]

**Review by nelsonkopliku — APPROVED** [review]
LGTM

**Review by fabriziosestito — COMMENTED** [review]
@ksanjeet thanks! 

We need [signed commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) to be able to merge.

**Comment by arbulu89** [comment]
> Signed the commit now, but it is showing as unverified.

Are the email of your gpg key and of your git author the same?
You can verify your configured email in git with: `git config --list` and the one for your gpg key with `gpg --list-secret-keys`
PD: Don't paste here the result

**Comment by ksanjeet** [comment]
They were different emails in the git config and the gpg. Let me fixed that. Thanks.

**Pull request merged**
