### PR TITLE
Refactor checks from when to metadata

### PR DESCRIPTION
**Pull request by nelsonkopliku**
Refactors checks to use metadata instead of when condition.

Gotta test the whole flow with checks having metadata and wanda's implementation here https://github.com/trento-project/wanda/pull/309 before merging

### CODE REVIEW

**Review by dottorblaster — APPROVED** [review]
No blockers from me

**Review by jamie-suse — APPROVED** [review]
LGTM :rocket:

**Comment by nelsonkopliku** [comment]
@abravosuse all these community checks are targeting clusters. What about the cluster type? Do they need specification in that regard?

**Comment by abravosuse** [comment]
@nelsonkopliku as discussed in the planning meeting, lets set the cluster type as HANA scale-up. I know some of the checks are also valid for ASCS/ERS clusters but let's leave that for the Checks Team.

**Pull request merged**
