### PR TITLE
Add a basic host check

### PR DESCRIPTION
**Pull request by nelsonkopliku**
For demo purposes.

### CODE REVIEW

**Review by EMaksy — COMMENTED** [review]
Hey the check by itself is great!
For development this will be very useful, we may still need to discuss if want to mix real checks with fake checks.
So code wise LGTM, let's hear what the rest thinks about including it or not :D

**Review by abravosuse — APPROVED** [review]
From the understanding I have about the check yaml, this looks good to me Nelson...

**Review by dottorblaster — COMMENTED** [review]
I'd rather not mix fake and real checks.

**Comment by nelsonkopliku** [comment]
> I'd rather not mix fake and real checks.

I promise I will delete it as soon as we have a _real_ host check.

Think of it as as a basic noop :sweat_smile:

**Comment by arbulu89** [comment]
I'm with @dottorblaster on this.
Why do we need to push this fake check?
Just to have the demo web updated? I though that the checks in the frontend would be disabled as we do with `ascs/ers` cluster types, with some sort of `Coming next` banner. Until we have something "real" to deliver

**Comment by nelsonkopliku** [comment]
Yes, we'll have the coming soon communication.

Nevertheless before adding the coming soon, we'll deliver a working feature that might be interesting testing.

If we don't like this I can ditch it. It will be just a bit more cumbersome testing host checks without the support of an engineer.

No hard feelings :smile:

**Pull request closed without merging**
